// <auto-generated />
using System;
using Inventario.Negocio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventario.Negocio.Migraciones
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20261003184441_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventario")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Negocio.Ordenes.LineaOrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<int>("OrdenDeCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_de_compra_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_lineas_orden_compra");

                    b.HasIndex("OrdenDeCompraId")
                        .HasDatabaseName("ix_lineas_orden_compra_orden_de_compra_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_lineas_orden_compra_producto_id");

                    b.ToTable("lineas_orden_compra", "inventario");
                });

            modelBuilder.Entity("Inventario.Negocio.Ordenes.OrdenDeCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.HasKey("Id")
                        .HasName("pk_ordenes_de_compra");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_ordenes_de_compra_proveedor_id");

                    b.ToTable("ordenes_de_compra", "inventario");
                });

            modelBuilder.Entity("Inventario.Negocio.Productos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("Existencia")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("existencia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PuntoReorden")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("punto_reorden");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_productos_sku");

                    b.ToTable("productos", "inventario");
                });

            modelBuilder.Entity("Inventario.Negocio.Proveedores.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.ToTable("proveedores", "inventario");
                });

            modelBuilder.Entity("Inventario.Negocio.Ordenes.LineaOrdenCompra", b =>
                {
                    b.HasOne("Inventario.Negocio.Ordenes.OrdenDeCompra", "OrdenDeCompra")
                        .WithMany("Lineas")
                        .HasForeignKey("OrdenDeCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_orden_compra_ordenes_de_compra_orden_de_compra_id");

                    b.HasOne("Inventario.Negocio.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_orden_compra_productos_producto_id");

                    b.Navigation("OrdenDeCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Inventario.Negocio.Ordenes.OrdenDeCompra", b =>
                {
                    b.HasOne("Inventario.Negocio.Proveedores.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordenes_de_compra_proveedores_proveedor_id");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Inventario.Negocio.Ordenes.OrdenDeCompra", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
