// <auto-generated />
using System;
using Inventario.Core.ControlAcceso;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventario.Core.ControlAcceso.Migraciones
{
    [DbContext(typeof(ControlAccesoDbContext))]
    partial class ControlAccesoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control_acceso")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Core.ControlAcceso.Cuentas.TokenActivacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("EmitidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emitido_en");

                    b.Property<string>("HashCodigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_codigo");

                    b.Property<DateTimeOffset?>("InvalidadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidado_en");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean")
                        .HasColumnName("usado");

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("VenceEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vence_en");

                    b.HasKey("Id")
                        .HasName("pk_tokens_activacion");

                    b.HasIndex("HashCodigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_activacion_hash_codigo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_tokens_activacion_usuario_id");

                    b.ToTable("tokens_activacion", "control_acceso");
                });

            modelBuilder.Entity("Inventario.Core.ControlAcceso.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", "control_acceso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Estándar"
                        });
                });

            modelBuilder.Entity("Inventario.Core.ControlAcceso.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActivadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activado_en");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol_id");

                    b.ToTable("usuarios", "control_acceso");
                });

            modelBuilder.Entity("Inventario.Core.ControlAcceso.Cuentas.TokenActivacion", b =>
                {
                    b.HasOne("Inventario.Core.ControlAcceso.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_activacion_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Inventario.Core.ControlAcceso.Usuario", b =>
                {
                    b.HasOne("Inventario.Core.ControlAcceso.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_rol_id");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
